# Required
version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Set OS and python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
