# Required
version: 2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Image to use
build:
  image: testing

# Configuration
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
