FROM python:3.10-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update

RUN pip install --upgrade pip
RUN pip install poetry

RUN mkdir /clean_text_rhoni
WORKDIR /clean_text_rhoni
COPY . /clean_text_rhoni

ENV PYTHONPATH=${PYTHONPATH}:${PWD}
RUN poetry config virtualenvs.create true

RUN poetry install

CMD [ "poetry", "run", "pytest", "tests/", "--cov=clean_text_rhoni", "--cov-report=xml" ]
