# Name of the workflow
name: ci-cd

# Controls when the workflow will run
on:
  # Triggers the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v3

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest tests/ --cov=pycounts --cov-report=xml

    - name: Build documentation
      run: poetry run make html --directory docs/
