name: ci-cd

jobs: 
  call-ci:
    uses: rhoni-team/clean_text_rhoni/.github/workflows/ci.yml@27.fix_ci_running_2_times

  call-cd:
    needs: call-ci
    uses: rhoni-team/clean_text_rhoni/.github/workflows/cd.yml@27.fix_ci_running_2_times
    secrets:
      semantic_release_key: ${{ secrets.SEMANTIC_RELEASE_KEY }}
      test_pypi_api_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
    permissions:
      contents: write
      id-token: write
