name: ci-cd

on:  
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  jobs: 
    call-ci:
      if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
      uses: rhoni-team/clean_text_rhoni/.github/workflows/ci.yml

    call-ci:
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: rhoni-team/clean_text_rhoni/.github/workflows/cd.yml
      secrets:
        semantic_release_key: ${{ secrets.SEMANTIC_RELEASE_KEY }}
        test_pypi_api_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
